### ISSUE TITLE
ADD 1380996178 RPTR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#104]
{
    "chainId": 1380996178,
    "url": "https://raptorchain.io",
    "ticker": "RPTR",
    "comment": "RaptorChain",
    "rpc": [
        "https://rpc.raptorchain.io/web3"
    ],
    "blockNumber": 298
}

**Comment by noxonsu** [comment]
https://raptorchain.io/bridge есть бридж, фармилка и прочие дапы. нечего предложить
