### ISSUE TITLE
ADD 462 AREA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#108]
{
    "chainId": 462,
    "url": "https://areon.network",
    "ticker": "AREA",
    "comment": "Areon Network Testnet",
    "rpc": [
        "https://testnet-rpc.areon.network"
    ],
    "dateAdd": "2023-09-08T00:06:59.413842",
    "blockNumber": 47078
}

**Comment by noxonsu** [comment]
бриджа нет 
группа https://t.me/areonnetwork 
https://t.me/CryptoChroniclesOG овнер

гитхаб https://github.com/areonnetwork
