### ISSUE TITLE
ADD 1089 HEART

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#109]
{
    "chainId": 1089,
    "url": "https://humans.ai",
    "ticker": "HEART",
    "comment": "Humans.ai Mainnet",
    "rpc": [
        "https://jsonrpc.humans.nodestake.top",
        "https://humans-mainnet-evm.itrocket.net:443",
        "https://humans-evm-rpc.staketab.org:443",
        "https://evm.humans.stakepool.dev.br",
        "https://mainnet-humans-evm.konsortech.xyz",
        "https://evm-rpc.mainnet.humans.zone"
    ],
    "dateAdd": "2023-09-08T00:06:59.413921",
    "blockNumber": 1514055
}

**Comment by noxonsu** [comment]
бриджа нет, но в меню есть серая ссылка, возможно хотят. 
https://t.me/humansdotai - группа 
https://t.me/AleexRaddu - админ 

есть дата запуска бриджа https://t.me/humansdotai/123615 :(

**Comment by noxonsu** [comment]
анонсы https://t.me/humansdotai_announcements
