### ISSUE TITLE
ADD 1133 DFI

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#110]
{
    "chainId": 1133,
    "url": "https://defichain.com",
    "ticker": "DFI",
    "comment": "DeFiMetaChain",
    "rpc": [
        "https://testnet-dmc.mydefichain.com:20551"
    ],
    "dateAdd": "2023-09-09T00:06:55.606417",
    "blockNumber": "Error: Expecting value: line 1 column 1 (char 0)"
}

**Comment by Andey0** [comment]
https://t.me/defiblockchain  анонсы 
https://t.me/Galxe_telegram_bot  админ
https://github.com/DeFiCh/ain  рипозиторий 
бридж есть
