### ISSUE TITLE
ADD 30103 CAU

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#111]
{
    "chainId": 30103,
    "url": "https://canxium.org",
    "ticker": "CAU",
    "comment": "Cerium Testnet",
    "rpc": [
        "https://cerium-rpc.canxium.net"
    ],
    "dateAdd": "2023-09-09T00:06:55.606648",
    "blockNumber": 372420
}

**Comment by Andey0** [comment]
https://t.me/Jonkerry  админ тг группы 
https://t.me/+y8Px8X8xjglkYmFl  сам тг 
https://github.com/canxium/go-canxium  рипозиторий
https://canxium.org/#tokensale-part  бридж

**Comment by noxonsu** [comment]
закрываем если есть бридж
