### ISSUE TITLE
ADD 12890 QNET

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#114]
{
    "chainId": 12890,
    "url": "https://quantumnetwork.gg",
    "ticker": "QNET",
    "comment": "Quantum Chain Testnet",
    "rpc": [
        "https://testnet-rpc.quantumscan.org"
    ],
    "dateAdd": "2023-09-11T00:07:17.053844",
    "blockNumber": 65366
}

**Comment by Andey0** [comment]
бридж есть 
телеграмма не открывается 
дискорд не открывается
гитхаба нету
