### ISSUE TITLE
ADD 1003 TET

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#116]
{
    "chainId": 1003,
    "url": "https://softnote.com",
    "ticker": "TET",
    "comment": "Tectum Emission Token",
    "rpc": [
        "https://rpc.softnote.com/"
    ],
    "dateAdd": "2023-09-12T00:06:56.855915",
    "blockNumber": 1911
}

**Comment by Andey0** [comment]
https://t.me/tectumglobal  телеграмм
https://github.com/intradept/erc20-generator  рипозиторий 
бридж есть админа не нашел
