### ISSUE TITLE
ADD 5522 VEX

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#122]
{
    "chainId": 5522,
    "url": "https://vexanium.com",
    "ticker": "VEX",
    "comment": "VEX EVM TESTNET",
    "rpc": [
        "https://testnet.vexascan.com/evmapi"
    ],
    "dateAdd": "2023-09-21T00:06:54.756261",
    "blockNumber": 506239
}

**Comment by noxonsu** [comment]
есть форум надо выложить сюда https://club.vexanium.com/
