### ISSUE TITLE
ADD 2241 KRST

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#123]
{
    "chainId": 2241,
    "url": "https://www.peaq.network",
    "ticker": "KRST",
    "comment": "The Krest Network",
    "rpc": [
        "https://erpc-krest.peaq.network"
    ],
    "dateAdd": "2023-09-22T00:06:52.279082",
    "blockNumber": 801036
}

**Comment by noxonsu** [comment]
слишком большие
