### ISSUE TITLE
ADD 38400 cmRPG

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#125]
{
    "chainId": 38400,
    "url": "https://rangersprotocol.com",
    "ticker": "cmRPG",
    "comment": "ConnectorManager",
    "rpc": [
        "https://cm.rangersprotocol.com/api/jsonrpc"
    ],
    "dateAdd": "2023-09-23T00:06:42.750101",
    "blockNumber": 16871
}

**Comment by noxonsu** [comment]
отправил письмо

subj: Your blockchain has about 17000 blocks, so maybe our tools can help.
Hi again, I'm Alex. I have a team that makes tools for blockchains. We have things like bridges between chains, DEX, lottery tools, DAOs, and NFT stuff. 

We sell them for a set price, but some can be used for free if we share the profits. Can I show you some examples? Waiting for your reply!
