### ISSUE TITLE
ADD 333666 tOONE

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#126]
{
    "chainId": 333666,
    "url": "https://oonechain.com",
    "ticker": "tOONE",
    "comment": "Oone Chain Testnet",
    "rpc": [
        "https://rpc.testnet.oonechain.com"
    ],
    "dateAdd": "2023-09-23T00:06:42.750207",
    "blockNumber": 75143
}

**Comment by noxonsu** [comment]
сайт не пашет
