### ISSUE TITLE
ADD 77238 tFNC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#127]
{
    "chainId": 77238,
    "url": "https://foundrychain.org",
    "ticker": "tFNC",
    "comment": "Foundry Chain Testnet",
    "rpc": [
        "https://testnet-rpc.foundryscan.org/"
    ],
    "dateAdd": "2023-09-24T00:07:41.389132",
    "blockNumber": 143225
}

**Comment by noxonsu** [comment]
все ссылки битые
