### ISSUE TITLE
ADD 963 BTCC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#132]
{
    "chainId": 963,
    "url": "https://bitcoincode.technology",
    "ticker": "BTCC",
    "comment": "BTC20 Smart Chain",
    "rpc": [
        "https://rpc.bitcoincode.technology/"
    ],
    "dateAdd": "2023-09-29T00:07:07.846733",
    "blockNumber": 200470
}

**Comment by noxonsu** [comment]
треш все ссылки битые
