### ISSUE TITLE
ADD 710 FURY

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#133]
{
    "chainId": 710,
    "url": "https://www.fury.black",
    "ticker": "FURY",
    "comment": "Highbury",
    "rpc": [
        "https://highbury.furya.io",
        "https://rest.furya.io"
    ],
    "dateAdd": "2023-09-30T00:06:54.021723",
    "blockNumber": 749849
}

**Comment by noxonsu** [comment]
рпс не работают публично написал пока тут https://twitter.com/noxonsu/status/1708839069193470113

**Comment by noxonsu** [comment]
https://t.me/highburychain группа

**Comment by noxonsu** [comment]
в группе есть админ @Eagle_Eye_007 отписал ему следующее. "hi I found a broken link on your website at https://fury.black/ (Ecosystem) . You might want to check it." если ответит попрошу емейл и отправлю пропозал
