### ISSUE TITLE
ADD 2049 MOVO

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#135]
{
    "chainId": 2049,
    "url": "https://movo.uk",
    "ticker": "MOVO",
    "comment": "Movo Smart Chain Mainnet",
    "rpc": [
        "https://msc-rpc.movoscan.com",
        "https://msc-rpc.movochain.org",
        "https://msc-rpc.movoswap.com"
    ],
    "dateAdd": "2023-10-02T00:07:29.517543",
    "blockNumber": 73359
}

**Comment by noxonsu** [comment]
пустой гитхаб https://github.com/movosmartchain?tab=repositories 
в твиттере написал им https://twitter.com/noxonsu/status/1708840903371075655 

```
Hi I've checked your rpc https://msc-rpc.movoscan.com and it's look good for new crosschain bridge. Let's talk how to connect it to eth/bsc etc..
```
