### ISSUE TITLE
ADD 776877 MDM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#141]
{
    "chainId": 776877,
    "url": "https://www.rmrk.app/",
    "ticker": "MDM",
    "comment": "Modularium",
    "rpc": [
        "https://fraa-dancebox-3035-rpc.a.dancebox.tanssi.network"
    ],
    "dateAdd": "2023-10-08T12:14:06.362049",
    "blockNumber": 25827
}

**Comment by noxonsu** [comment]
большой проект по nft на сайдчейне полькадота, пока изучаю
