### ISSUE TITLE
ADD 8668 HLUSD

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#143]
{
    "chainId": 8668,
    "url": "https://helalabs.com",
    "ticker": "HLUSD",
    "comment": "Hela Official Runtime Mainnet",
    "rpc": [
        "https://mainnet-rpc.helachain.com"
    ],
    "dateAdd": "2023-10-10T00:07:01.958270",
    "blockNumber": 1938
}

**Comment by noxonsu** [comment]
отправил через форму
