### ISSUE TITLE
ADD 666888 HLUSD

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#144]
{
    "chainId": 666888,
    "url": "https://helalabs.com",
    "ticker": "HLUSD",
    "comment": "Hela Official Runtime Testnet",
    "rpc": [
        "https://testnet-rpc.helachain.com"
    ],
    "dateAdd": "2023-10-10T00:07:01.958492",
    "blockNumber": 27309
}

**Comment by noxonsu** [comment]
https://github.com/noxonsu/chains/issues/143
