### ISSUE TITLE
ADD 210 BTN

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#15]
{
    "chainId": 210,
    "url": "https://bitnet.money",
    "ticker": "BTN",
    "comment": "Bitnet",
    "rpc": [
        "https://rpc.bitnet.money",
        "https://rpc.btnscan.com"
    ],
    "eth_gtbbIndexResponce": {
        "jsonrpc": "2.0",
        "id": 1,
        "result": null
    },
    "blockNumber": 372478
}

**Comment by Andey0** [comment]
https://t.me/MarzoM3  админ тг 
https://github.com/BitnetMoney/bitnet  рипозиторий 
https://t.me/Bitnet_Official_Group  тг канал
бридж есть
