### ISSUE TITLE
ADD 236 DEAM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#16]
{
    "chainId": 236,
    "url": "https://deamchain.com",
    "ticker": "DEAM",
    "comment": "Deamchain Testnet",
    "rpc": [
        "https://testnet.deamchain.com"
    ],
    "blockNumber": 8703
}

**Comment by Andey0** [comment]
https://t.me/deamchain   телеграмм
https://t.me/GroupHelpBot   админ
бридж есть 
гитхаба не нашел
