### ISSUE TITLE
ADD 259 NEON

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#18]
{
    "chainId": 259,
    "url": "https://neonlink.io",
    "ticker": "NEON",
    "comment": "Neonlink Mainnet",
    "rpc": [
        "https://mainnet.neonlink.io"
    ],
    "eth_gtbbIndexResponce": {
        "jsonrpc": "2.0",
        "id": 1,
        "result": {
            "blockHash": "0x000000010000000154b7264f740df32f75125fcf2175e5ada8158471f8dec45d",
            "blockNumber": "0x1",
            "from": "0x0000000000000000000000000000000000000000",
            "gas": "0x2540be400",
            "gasPrice": "0x0",
            "hash": "0x75463d6d9b2ec487acaf85b6afdc6c12b03b8770f047087577a5f62532a95edc",
            "input": "0xc80e151300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000033b2e3c9fd0803ce8000000000000000000000000000000eab1000000000000000000000000000000000000000000000000000000000000eab10000000000000000000000000000000001ea000000000000000000000000eab100000000000000000000000000000000001e000000000000000000000000d100ec0000000000000000000000000000000000000000000000000000000000a3607a6bb324bfe38ae88f3aff23504449f0a34b",
            "nonce": "0x0",
            "to": "0xeab1000000000000000000000000000000000111",
            "transactionIndex": "0x0",
            "value": "0x0",
            "type": "0x0",
            "v": "0x0",
            "r": "0x0",
            "s": "0x0"
        }
    },
    "blockNumber": 29625
}

**Comment by Andey0** [comment]
https://t.me/NeonLinkGaming  телеграмм
https://t.me/MissRose_bot  админ
бридж есть 
гитхаба нету
