### ISSUE TITLE
ADD 297 HBAR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#19]
{
    "chainId": 297,
    "url": "https://hedera.com",
    "ticker": "HBAR",
    "comment": "Hedera Previewnet",
    "rpc": [
        "https://previewnet.hashio.io/api"
    ],
    "eth_gtbbIndexResponce": {
        "result": null,
        "jsonrpc": "2.0",
        "id": 1
    },
    "blockNumber": 463777
}

**Comment by Andey0** [comment]
https://t.me/Bitnet_Official_Group  тг чат людей мне не показывало поэтому не смог написать админа
https://hedera.com/ бридж (то есть сам сайт)
github нету
