### ISSUE TITLE
ADD 500 CAM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#21]
{
    "chainId": 500,
    "url": "https://camino.network/",
    "ticker": "CAM",
    "comment": "Camino C-Chain",
    "rpc": [
        "https://api.camino.network/ext/bc/C/rpc"
    ],
    "blockNumber": 6841
}

**Comment by Andey0** [comment]
https://t.me/camino_network телеграмм
админа не нашел
https://github.com/chain4travel/caminogo рипозиторий
бридж не нашел
