### ISSUE TITLE
ADD 7100 DAI

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#225]
{
    "chainId": 7100,
    "url": "https://numecrypto.com",
    "ticker": "DAI",
    "comment": "Nume",
    "rpc": [
        "https://rpc.numecrypto.com"
    ],
    "dateAdd": "2023-12-22T00:07:30.339509",
    "blockNumber": "Unknown"
}

**Comment by Dians3934** [comment]
mailto:support@numecrypto.com
