### ISSUE TITLE
ADD 8087 USD

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#236]
{
    "chainId": 8087,
    "url": "https://e-dollar.org",
    "ticker": "USD",
    "comment": "E-Dollar",
    "rpc": [
        "https://rpc.e-dollar.org"
    ],
    "dateAdd": "2023-12-28T00:07:19.219818",
    "blockNumber": 11264
}

**Comment by Dians3934** [comment]
peerpaycorp@gmail.com
