### ISSUE TITLE
ADD 595 mACA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#24]
{
    "chainId": 595,
    "url": "https://acala.network",
    "ticker": "mACA",
    "comment": "Acala Mandala Testnet TC9",
    "rpc": [
        "https://eth-rpc-tc9.aca-staging.network",
        "wss://eth-rpc-tc9.aca-staging.network"
    ],
    "blockNumber": 569455
}

**Comment by Andey0** [comment]
https://t.me/Alex_acala  админ тг 
https://t.me/acalaofficial  сам тг 
https://github.com/AcalaNetwork/Acala рипозиторий
https://apps.acala.network/swap  бридж
