### ISSUE TITLE
ADD 10242 AA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#242]
{
    "chainId": 10242,
    "url": "https://docs.arthera.net/build/developing-sc/using-hardhat",
    "ticker": "AA",
    "comment": "Arthera Mainnet",
    "rpc": [
        "https://rpc.arthera.net"
    ],
    "dateAdd": "2024-01-05T00:07:32.934454",
    "blockNumber": 1312
}

**Comment by Dians3934** [comment]
https://t.me/artherachain/1648/91979
