### ISSUE TITLE
ADD 5169 SU

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#243]
{
    "chainId": 5169,
    "url": "https://www.smartlayer.network/",
    "ticker": "SU",
    "comment": "Smart Layer Network",
    "rpc": [
        "https://rpc.main.smartlayer.network"
    ],
    "dateAdd": "2024-01-06T00:07:21.866025",
    "blockNumber": 0
}

**Comment by Dians3934** [comment]
sayhi@smarttokenlabs.com
