### ISSUE TITLE
ADD 8726 STOR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#245]
{
    "chainId": 8726,
    "url": "https://storagechain.io/about-us",
    "ticker": "STOR",
    "comment": "Storagechain Mainnet",
    "rpc": [
        "https://mainnet-validator.storagechain.io"
    ],
    "dateAdd": "2024-01-06T00:07:21.866092",
    "blockNumber": 1898555
}

**Comment by Dians3934** [comment]
https://t.me/StorageChainOfficialChat/10146
