### ISSUE TITLE
ADD 9888 DOGE

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#247]
{
    "chainId": 9888,
    "url": "https://dogelayer.org",
    "ticker": "DOGE",
    "comment": "Dogelayer Mainnet",
    "rpc": [
        "https://dl-rpc.dogelayer.org"
    ],
    "dateAdd": "2024-01-06T00:07:21.866110",
    "blockNumber": 166982
}

**Comment by Dians3934** [comment]
https://t.me/DogeLayerGlobal/618
