### ISSUE TITLE
ADD 42355 GOLDX

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#249]
{
    "chainId": 42355,
    "url": "https://goldxchain.io",
    "ticker": "GOLDX",
    "comment": "GoldXChain Mainnet",
    "rpc": [
        "https://mainnet-rpc.goldxchain.io"
    ],
    "dateAdd": "2024-01-06T00:07:21.866173",
    "blockNumber": 2151334
}

**Comment by Dians3934** [comment]
https://t.me/fusegold/401372
