### ISSUE TITLE
ADD 571 MTC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#251]
{
    "chainId": 571,
    "url": "https://metatime.com/en",
    "ticker": "MTC",
    "comment": "MetaChain Mainnet",
    "rpc": [
        "https://rpc.metatime.com"
    ],
    "dateAdd": "2024-01-10T00:07:26.321042",
    "blockNumber": 348207
}

**Comment by Dians3934** [comment]
https://t.me/metatime/177450
