### ISSUE TITLE
ADD 654 KALIS

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#252]
{
    "chainId": 654,
    "url": "https://kalichain.com",
    "ticker": "KALIS",
    "comment": "Kalichain",
    "rpc": [
        "https://mainnet.kalichain.com"
    ],
    "dateAdd": "2024-01-10T00:07:26.321059",
    "blockNumber": 3176
}

**Comment by Dians3934** [comment]
Нет группы в телеграмме

**Comment by Dians3934** [comment]
https://t.me/kalichain/167917/201354
