### ISSUE TITLE
ADD 4243 NEXI

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#253]
{
    "chainId": 4243,
    "url": "https://www.nexi.technology/",
    "ticker": "NEXI",
    "comment": "Nexi V2 Mainnet",
    "rpc": [
        "https://chain.nexiv2.nexilix.com",
        "https://rpc.chainv1.nexi.technology"
    ],
    "dateAdd": "2024-01-10T00:07:26.321221",
    "blockNumber": 647317
}

**Comment by Dians3934** [comment]
Личные данные https://t.me/nexinetwork

**Comment by noxonsu** [comment]
у него в тексе KALIS ((
