### ISSUE TITLE
ADD 128123 XTZ

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#254]
{
    "chainId": 128123,
    "url": "https://etherlink.com",
    "ticker": "XTZ",
    "comment": "Etherlink Testnet",
    "rpc": [
        "https://node.ghostnet.etherlink.com"
    ],
    "dateAdd": "2024-01-10T00:07:26.321421",
    "blockNumber": 570004
}

**Comment by Dians3934** [comment]
Стоит блок на боты, сообщение удалили и выкинули с группы
