### ISSUE TITLE
ADD 879151 BLX

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#256]
{
    "chainId": 879151,
    "url": "https://www.blocxchain.org/",
    "ticker": "BLX",
    "comment": "BlocX Mainnet",
    "rpc": [
        "https://mainnet-rpc.blxscan.com/"
    ],
    "dateAdd": "2024-01-10T00:07:26.321467",
    "blockNumber": 2055722
}

**Comment by Dians3934** [comment]
на сайте нет телеграмма
