### ISSUE TITLE
ADD 129 JNFTC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#258]
{
    "chainId": 129,
    "url": "https://jumbochain.org",
    "ticker": "JNFTC",
    "comment": "ProtoJumbo Testnet",
    "rpc": [
        "https://testnode.jumbochain.org"
    ],
    "dateAdd": "2024-01-15T00:08:14.453217",
    "blockNumber": 1411883
}

**Comment by Dians3934** [comment]
https://t.me/jumbochainofficial/39082
