### ISSUE TITLE
ADD 668 JGC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#26]
{
    "chainId": 668,
    "url": "https://junca-cash.world",
    "ticker": "JGC",
    "comment": "JuncaChain",
    "rpc": [
        "https://rpc.juncachain.com"
    ],
    "blockNumber": 233651
}

**Comment by Andey0** [comment]
https://t.me/juncafangroup  телеграмм
https://t.me/junca_admin  админ
бридж не нашел 
гитхаба не нашел
