### ISSUE TITLE
ADD 3799 tTNT

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#260]
{
    "chainId": 3799,
    "url": "https://docs.tangle.tools",
    "ticker": "tTNT",
    "comment": "Tangle Testnet",
    "rpc": [
        "https://testnet-rpc.tangle.tools",
        "https://testnet-rpc-archive.tangle.tools",
        "wss://testnet-rpc.tangle.tools",
        "wss://testnet-rpc-archive.tangle.tools"
    ],
    "dateAdd": "2024-01-15T00:08:14.453429",
    "blockNumber": 78450
}

**Comment by Dians3934** [comment]
https://t.me/webbprotocol/2181
