### ISSUE TITLE
ADD 45510 DEE

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#261]
{
    "chainId": 45510,
    "url": "https://deelance.com",
    "ticker": "DEE",
    "comment": "Deelance Mainnet",
    "rpc": [
        "https://rpc.deelance.com"
    ],
    "dateAdd": "2024-01-15T00:08:14.453568",
    "blockNumber": "Error: Expecting value: line 1 column 1 (char 0)"
}

**Comment by Dians3934** [comment]
Телеграмм есть, но запрещено писать

**Comment by Dians3934** [comment]
https://t.me/deelance_com blockNumber

**Comment by Dians3934** [comment]
info@deelance.com)
