### ISSUE TITLE
ADD 6701 PAXB

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#262]
{
    "chainId": 6701,
    "url": "https://paxb.io/",
    "ticker": "PAXB",
    "comment": "PAXB Mainnet",
    "rpc": [
        "https://chain.paxb.io"
    ],
    "dateAdd": "2024-01-16T00:07:33.345784",
    "blockNumber": 2002394
}

**Comment by Dians3934** [comment]
https://t.me/PAXB_official_COMM/31454
