### ISSUE TITLE
ADD 9395 MTHN

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#263]
{
    "chainId": 9395,
    "url": "https://explorer.evokescan.org",
    "ticker": "MTHN",
    "comment": "Evoke Mainnet",
    "rpc": [
        "https://mainnet-rpc.evokescan.org"
    ],
    "dateAdd": "2024-01-16T00:07:33.345836",
    "blockNumber": 13899037
}

**Comment by Dians3934** [comment]
Телеграмм есть, но запрещено писать
