### ISSUE TITLE
ADD 20765 JONO

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#268]
{
    "chainId": 20765,
    "url": "",
    "ticker": "JONO",
    "comment": "Jono11 Subnet",
    "rpc": [
        "https://subnets.avax.network/jono11/testnet/rpc"
    ],
    "dateAdd": "2024-01-25T00:07:36.939797",
    "blockNumber": 4753
}

**Comment by Dians3934** [comment]
на сайте нет телеграмма

**Comment by Dians3934** [comment]
https://t.me/Avalancheavax_officialENG/8906
