### ISSUE TITLE
ADD 25186 LILA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#272]
{
    "chainId": 25186,
    "url": "https://scan.liquidlayer.network",
    "ticker": "LILA",
    "comment": "LiquidLayer Mainnet",
    "rpc": [
        "https://mainnet.liquidlayer.network"
    ],
    "dateAdd": "2024-01-26T00:07:18.704211",
    "blockNumber": 310343
}

**Comment by Dians3934** [comment]
https://t.me/LiquidLayer/116739
