### ISSUE TITLE
ADD 9024 NEXB

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#275]
{
    "chainId": 9024,
    "url": "https://www.nexablock.io/",
    "ticker": "NEXB",
    "comment": "Nexa Block",
    "rpc": [
        "https://rpc-testnet-nodes.nexablockscan.io"
    ],
    "dateAdd": "2024-01-28T00:08:00.692867",
    "blockNumber": 873677
}

**Comment by Dians3934** [comment]
Группа в телеге есть, но посты запрещено писать.
