### ISSUE TITLE
ADD 80085 BERA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#277]
{
    "chainId": 80085,
    "url": "https://www.berachain.com",
    "ticker": "BERA",
    "comment": "Berachain Artio",
    "rpc": [
        "https://artio.rpc.berachain.com",
        "https://rpc.ankr.com/berachain_testnet"
    ],
    "dateAdd": "2024-01-28T00:08:00.692989",
    "blockNumber": 304853
}

**Comment by Dians3934** [comment]
В чате нельзя писать
