### ISSUE TITLE
ADD 955081 JONO

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#278]
{
    "chainId": 955081,
    "url": "",
    "ticker": "JONO",
    "comment": "Jono12 Subnet",
    "rpc": [
        "https://subnets.avax.network/jono12/testnet/rpc"
    ],
    "dateAdd": "2024-01-28T00:08:00.693061",
    "blockNumber": 16405
}

**Comment by Dians3934** [comment]
Нет почты и группы в телеграмме.

**Comment by Dians3934** [comment]
https://t.me/avalancheavax/411936
