### ISSUE TITLE
ADD 323 CVM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#280]
{
    "chainId": 323,
    "url": "https://cosvm.network",
    "ticker": "CVM",
    "comment": "Cosvm Mainnet",
    "rpc": [
        "https://rpc.cosvm.net"
    ],
    "dateAdd": "2024-01-30T00:07:14.336299",
    "blockNumber": 966270
}

**Comment by Dians3934** [comment]
https://t.me/CosVMCommunity/8902
