### ISSUE TITLE
ADD 713 VRC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#281]
{
    "chainId": 713,
    "url": "https://vrccoin.com",
    "ticker": "VRC",
    "comment": "Vrcscan Mainnet",
    "rpc": [
        "https://rpc-mainnet-5.vrcscan.com",
        "https://rpc-mainnet-6.vrcscan.com",
        "https://rpc-mainnet-7.vrcscan.com",
        "https://rpc-mainnet-8.vrcscan.com"
    ],
    "dateAdd": "2024-01-30T00:07:14.336344",
    "blockNumber": 400517
}

**Comment by Dians3934** [comment]
Телеграмм есть, но как поняла удален или не добавлен

**Comment by Dians3934** [comment]
https://t.me/VZSolutions/74
