### ISSUE TITLE
ADD 7007 BSTC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#283]
{
    "chainId": 7007,
    "url": "https://bstchain.io",
    "ticker": "BSTC",
    "comment": "BST Chain",
    "rpc": [
        "https://rpc.bstchain.io/"
    ],
    "dateAdd": "2024-01-30T00:07:14.336517",
    "blockNumber": 1082328
}

**Comment by Dians3934** [comment]
https://t.me/bstokens_official/120497
