### ISSUE TITLE
ADD 21133 AAH

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#284]
{
    "chainId": 21133,
    "url": "https://c4ex.net",
    "ticker": "AAH",
    "comment": "All About Healthy",
    "rpc": [
        "https://rpc.c4ex.net"
    ],
    "dateAdd": "2024-01-30T00:07:14.336595",
    "blockNumber": 189206
}

**Comment by Dians3934** [comment]
https://t.me/c4eiAirdrop/104779
