### ISSUE TITLE
ADD 56797 DOID

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#286]
{
    "chainId": 56797,
    "url": "https://doid.tech",
    "ticker": "DOID",
    "comment": "DOID Testnet",
    "rpc": [
        "https://rpc.testnet.doid.tech"
    ],
    "dateAdd": "2024-01-30T00:07:14.336640",
    "blockNumber": 5310
}

**Comment by Dians3934** [comment]
на сайте нет телеграмма
