### ISSUE TITLE
ADD 713715 SEI

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#296]
{
    "chainId": 713715,
    "url": "https://www.sei.io",
    "ticker": "SEI",
    "comment": "Sei Devnet",
    "rpc": [
        "https://evm-rpc-arctic-1.sei-apis.com",
        "https://evm-rpc.arctic-1.seinetwork.io"
    ],
    "dateAdd": "2024-02-03T00:07:17.581972",
    "blockNumber": 1493116
}

**Comment by Dians3934** [comment]
https://t.me/seinetwork/1/270063
