### ISSUE TITLE
ADD 842 TARA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#30]
{
    "chainId": 842,
    "url": "https://taraxa.io",
    "ticker": "TARA",
    "comment": "Taraxa Testnet",
    "rpc": [
        "https://rpc.testnet.taraxa.io/"
    ],
    "blockNumber": 444086
}

**Comment by Andey0** [comment]
https://t.me/taraxa_project  телеграмм
https://t.me/reno_taraxa  админ
https://github.com/Taraxa-project/taraxa-node  рипозиторий
бридж нету
