### ISSUE TITLE
ADD 422 VRD

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#301]
{
    "chainId": 422,
    "url": "https://viridis.network",
    "ticker": "VRD",
    "comment": "Viridis Mainnet",
    "rpc": [
        "https://mainnet-rpc.vrd.network"
    ],
    "dateAdd": "2024-02-13T00:07:30.591409",
    "blockNumber": 1027742
}

**Comment by Dians3934** [comment]
team@viridis.network
https://t.me/ViridisNetwork/42574
