### ISSUE TITLE
ADD 78600 VG

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#306]
{
    "chainId": 78600,
    "url": "https://vanarchain.com",
    "ticker": "VG",
    "comment": "Vanguard",
    "rpc": [
        "https://rpc-vanguard.vanarchain.com",
        "wss://ws-vanguard.vanarchain.com"
    ],
    "dateAdd": "2024-02-13T00:07:30.591776",
    "blockNumber": 934189
}

**Comment by Dians3934** [comment]
https://t.me/vanarofficial/370457/397875
