### ISSUE TITLE
ADD 2410 KRK

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#310]
{
    "chainId": 2410,
    "url": "https://karak.network",
    "ticker": "KRK",
    "comment": "Karak Mainnet",
    "rpc": [
        "https://rpc.karak.network"
    ],
    "dateAdd": "2024-02-14T00:07:16.496151",
    "blockNumber": 2236911
}

**Comment by Dians3934** [comment]
https://t.me/Karak_Network/383

**Comment by Dians3934** [comment]
На сообщения есть реакция

**Comment by Dians3934** [comment]
https://discord.com/invite/7nJEVrw4Fh

https://discord.gg/JUFUdyCV

.tooney

raoufbenhar

Это взято с диалога  https://t.me/Cal_ambur
