### ISSUE TITLE
ADD 1961 SEL

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#314]
{
    "chainId": 1961,
    "url": "https://selendra.org",
    "ticker": "SEL",
    "comment": "Selendra Network Mainnet",
    "rpc": [
        "https://rpc0.selendra.org",
        "https://rpc1.selendra.org"
    ],
    "dateAdd": "2024-02-22T00:07:00.110523",
    "blockNumber": 2522782
}

**Comment by Dians3934** [comment]
https://t.me/selendranetwork/27729
