### ISSUE TITLE
ADD 1453 MTC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#317]
{
    "chainId": 1453,
    "url": "https://metatime.com/en",
    "ticker": "MTC",
    "comment": "MetaChain Istanbul",
    "rpc": [
        "https://istanbul-rpc.metachain.dev"
    ],
    "dateAdd": "2024-02-24T00:06:51.182802",
    "blockNumber": 539460
}

**Comment by Dians3934** [comment]
https://t.me/metatime/180405
