### ISSUE TITLE
ADD 1617 ETINS

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#319]
{
    "chainId": 1617,
    "url": "https://www.etins.org",
    "ticker": "ETINS",
    "comment": "Ethereum Inscription Mainnet",
    "rpc": [
        "https://rpc.etins.org"
    ],
    "dateAdd": "2024-03-01T00:08:20.765952",
    "blockNumber": 54791
}

**Comment by Dians3934** [comment]
https://t.me/ALLBESTICO/1/141970
