### ISSUE TITLE
ADD 222555 DEEPL

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#323]
{
    "chainId": 222555,
    "url": "https://deeplnetwork.org",
    "ticker": "DEEPL",
    "comment": "DeepL Mainnet",
    "rpc": [
        "https://rpc.deeplnetwork.org"
    ],
    "dateAdd": "2024-03-02T00:06:49.724124",
    "blockNumber": 44734
}

**Comment by Dians3934** [comment]
admin@deeplnet.org
