### ISSUE TITLE
ADD 7778 ORE

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#335]
{
    "chainId": 7778,
    "url": "https://orenium.org",
    "ticker": "ORE",
    "comment": "Orenium Mainnet Protocol",
    "rpc": [
        "https://validator-mainnet.orenium.org",
        "https://rpc-oracle-mainnet.orenium.org",
        "https://portalmainnet.orenium.org"
    ],
    "dateAdd": "2024-03-15T00:06:58.313015",
    "blockNumber": 5752
}

**Comment by Dians3934** [comment]
https://t.me/OreniumProtocol/136933
