### ISSUE TITLE
ADD 9898 LRS

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#337]
{
    "chainId": 9898,
    "url": "https://larissa.network",
    "ticker": "LRS",
    "comment": "Larissa Chain",
    "rpc": [
        "https://rpc.larissa.network"
    ],
    "dateAdd": "2024-03-15T00:06:58.313055",
    "blockNumber": 419533
}

**Comment by Dians3934** [comment]
https://t.me/HubbleExchange/21422
