### ISSUE TITLE
ADD 45454 SWP

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#341]
{
    "chainId": 45454,
    "url": "https://www.swamps.fi",
    "ticker": "SWP",
    "comment": "Swamps L2",
    "rpc": [
        "https://swamps.tc.l2aas.com"
    ],
    "dateAdd": "2024-03-19T00:07:07.125356",
    "blockNumber": 893632
}

**Comment by Dians3934** [comment]
https://t.me/swampssrc/1/2796
