### ISSUE TITLE
ADD 80002 MATIC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#342]
{
    "chainId": 80002,
    "url": "https://polygon.technology/",
    "ticker": "MATIC",
    "comment": "Amoy",
    "rpc": [
        "https://rpc-amoy.polygon.technology"
    ],
    "dateAdd": "2024-03-19T00:07:07.125392",
    "blockNumber": 4813599
}

**Comment by Dians3934** [comment]
https://t.me/polygonofficial/1243819
