### ISSUE TITLE
ADD 1291 SWTR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#39]
{
    "chainId": 1291,
    "url": "https://www.swisstronik.com",
    "ticker": "SWTR",
    "comment": "Swisstronik Testnet",
    "rpc": [
        "https://json-rpc.testnet.swisstronik.com"
    ],
    "blockNumber": 874863
}

**Comment by Andey0** [comment]
https://t.me/swisstronik  телеграмм 
https://github.com/SigmaGmbH/wallet-core  рипозиторий 
бридж не нашел
