### ISSUE TITLE
ADD 1353 CIC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#40]
{
    "chainId": 1353,
    "url": "https://www.cicchain.net",
    "ticker": "CIC",
    "comment": "CIC Chain Mainnet",
    "rpc": [
        "https://xapi.cicscan.com"
    ],
    "blockNumber": 560970
}

**Comment by Andey0** [comment]
https://t.me/elitheumcic тг канал (чат)
https://cicscan.com/  бридж 
https://t.me/EliteCEO контакт
https://t.me/JamesG_CIC  контакт 2
