### ISSUE TITLE
ADD 61406 KEC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#400]
{
    "chainId": 61406,
    "url": "https://kaichain.net",
    "ticker": "KEC",
    "comment": "KaiChain",
    "rpc": [
        "https://mainnet-rpc.kaichain.net"
    ],
    "dateAdd": "2024-04-11T00:07:25.572286",
    "blockNumber": 18823167
}

**Comment by Dians3934** [comment]
https://t.me/officialkaichain/89565
