### ISSUE TITLE
ADD 526916 DCT

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#401]
{
    "chainId": 526916,
    "url": "https://docoin.network",
    "ticker": "DCT",
    "comment": "DoCoin Community Chain",
    "rpc": [
        "https://rpc.docoin.shop"
    ],
    "dateAdd": "2024-04-11T00:07:25.572399",
    "blockNumber": 352801
}

**Comment by Dians3934** [comment]
https://t.me/DoCoinCommunity/4178
