### ISSUE TITLE
ADD 888882 REXX

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#402]
{
    "chainId": 888882,
    "url": "https://rexxnetwork.com",
    "ticker": "REXX",
    "comment": "REXX Mainnet",
    "rpc": [
        "https://rpc.rexxnetwork.com"
    ],
    "dateAdd": "2024-04-11T00:07:25.572416",
    "blockNumber": 1065467
}

**Comment by Dians3934** [comment]
https://t.me/rexxcoin/86363
