### ISSUE TITLE
ADD 1379 KLC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#41]
{
    "chainId": 1379,
    "url": "https://kalarchain.tech",
    "ticker": "KLC",
    "comment": "Kalar Chain",
    "rpc": [
        "https://rpc-api.kalarchain.tech"
    ],
    "blockNumber": 244753
}

**Comment by Andey0** [comment]
https://t.me/Sourave_e  админ тг 
https://t.me/kalarchain  тг чат 
https://github.com/KalarChain/chains  рипозиторий  
https://www.mexc.com/ru-RU/exchange/KLC_USDT  бридж
