### ISSUE TITLE
ADD 2040 VANRY

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#410]
{
    "chainId": 2040,
    "url": "https://vanarchain.com",
    "ticker": "VANRY",
    "comment": "Vanar Mainnet",
    "rpc": [
        "https://rpc.vanarchain.com",
        "wss://ws.vanarchain.com"
    ],
    "dateAdd": "2024-04-16T00:07:11.871101",
    "blockNumber": 432144
}

**Comment by Dians3934** [comment]
https://t.me/vanarofficial/1/440564
