### ISSUE TITLE
ADD 27181 KLAOS

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#413]
{
    "chainId": 27181,
    "url": "https://www.laosfoundation.io/",
    "ticker": "KLAOS",
    "comment": "KLAOS Nova",
    "rpc": [
        "https://rpc.klaosnova.laosfoundation.io",
        "wss://rpc.klaosnova.laosfoundation.io"
    ],
    "dateAdd": "2024-04-17T00:07:40.814284",
    "blockNumber": 26395
}

**Comment by Dians3934** [comment]
[info@laosfoundation.io
