### ISSUE TITLE
ADD 2153 FRA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#52]
{
    "chainId": 2153,
    "url": "https://findora.org/",
    "ticker": "FRA",
    "comment": "Findora Testnet",
    "rpc": [
        "https://prod-testnet.prod.findora.org:8545/"
    ],
    "blockNumber": 416909
}

**Comment by Andey0** [comment]
https://t.me/danielfindog  админ тг чата 
https://t.me/findoraen  сам тг чат 
https://findora.org/token/  бридж
