### ISSUE TITLE
ADD 2199 SAMA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#53]
{
    "chainId": 2199,
    "url": "https://moonsama.com",
    "ticker": "SAMA",
    "comment": "Moonsama Network",
    "rpc": [
        "https://rpc.moonsama.com",
        "wss://rpc.moonsama.com/ws"
    ],
    "blockNumber": 286906
}

**Comment by Andey0** [comment]
https://t.me/MoonsamaNFT  телеграмм
https://t.me/MissRose_bot  админ 
бридж не нашел 
гитхаба не нашел
