### ISSUE TITLE
ADD 2323 tSMA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#54]
{
    "chainId": 2323,
    "url": "https://somanetwork.io",
    "ticker": "tSMA",
    "comment": "SOMA Network Testnet",
    "rpc": [
        "https://data-testnet-v1.somanetwork.io/",
        "https://testnet-au-server-2.somanetwork.io",
        "https://testnet-au-server-1.somanetwork.io",
        "https://testnet-sg-server-1.somanetwork.io",
        "https://testnet-sg-server-2.somanetwork.io"
    ],
    "blockNumber": 329044
}

**Comment by Andey0** [comment]
https://t.me/Soma_community  тг канал 
[@BuyBotTech ](https://t.me/Soma_SupportBot) админ тг канала 
https://pancakeswap.finance/swap?outputCurrency=0xb5607c01915C22a841ef72e658Cb31Cd925968d9  бридж
