### ISSUE TITLE
ADD 4328 BOBA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#59]
{
    "chainId": 4328,
    "url": "https://boba.network",
    "ticker": "BOBA",
    "comment": "Bobafuji Testnet",
    "rpc": [
        "https://testnet.avax.boba.network",
        "wss://wss.testnet.avax.boba.network",
        "https://replica.testnet.avax.boba.network"
    ],
    "blockNumber": 3167
}

**Comment by Andey0** [comment]
https://t.me/bobanetwork  телеграмм
https://t.me/MissRose_bot  админ 
https://github.com/bobanetwork/v3-anchorage  рипозиторий
бридж есть
