### ISSUE TITLE
ADD 5353 tTRN

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#61]
{
    "chainId": 5353,
    "url": "https://tritanium.network",
    "ticker": "tTRN",
    "comment": "Tritanium Testnet",
    "rpc": [
        "https://nodetestnet-station-one.tritanium.network/",
        "https://nodetestnet-station-two.tritanium.network/"
    ],
    "blockNumber": 30304
}

**Comment by Andey0** [comment]
https://t.me/TritaniumGroup  телеграм чат 
https://github.com/tritaniumnetwork/frontend-configs  рипозиторий
https://docs.tritanium.wiki/guide/tritan-wallet-multichain  бридж
