### ISSUE TITLE
ADD 5678 Unit

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#63]
{
    "chainId": 5678,
    "url": "https://tanssi.network",
    "ticker": "Unit",
    "comment": "Tanssi EVM ContainerChain",
    "rpc": [
        "https://fraa-dancebox-3001-rpc.a.dancebox.tanssi.network",
        "wss://fraa-dancebox-3001-rpc.a.dancebox.tanssi.network"
    ],
    "blockNumber": 177696
}

**Comment by Andey0** [comment]
https://t.me/tanssiofficial  телеграмм
https://t.me/combot  админ 
https://github.com/moondance-labs/tanssi  рипозиторий 
бридж не нашел
