### ISSUE TITLE
ADD 5700 tSYS

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#64]
{
    "chainId": 5700,
    "url": "https://syscoin.org",
    "ticker": "tSYS",
    "comment": "Syscoin Tanenbaum Testnet",
    "rpc": [
        "https://rpc.tanenbaum.io",
        "wss://rpc.tanenbaum.io/wss",
        "https://syscoin-tanenbaum-evm.publicnode.com"
    ],
    "blockNumber": 346755
}

**Comment by Andey0** [comment]
https://t.me/OneDigitalCrypto  админ группы тг 
https://t.me/Syscoin_Official  сам тг канал (чат)
https://github.com/syscoin/sysethereum-contracts  рипозиторий 
https://syscoin.org/get-sys  бридж
