### ISSUE TITLE
ADD 7777 NMAC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#66]
{
    "chainId": 7777,
    "url": "https://riseofthewarbots.com/",
    "ticker": "NMAC",
    "comment": "Rise of the Warbots Testnet",
    "rpc": [
        "https://testnet1.riseofthewarbots.com",
        "https://testnet2.riseofthewarbots.com",
        "https://testnet3.riseofthewarbots.com",
        "https://testnet4.riseofthewarbots.com",
        "https://testnet5.riseofthewarbots.com"
    ],
    "blockNumber": 35030
}

**Comment by Andey0** [comment]
https://t.me/WarbotsOfficial  телеграмм
