### ISSUE TITLE
ADD 8181 tBOC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#69]
{
    "chainId": 8181,
    "url": "https://testnet.beonescan.com",
    "ticker": "tBOC",
    "comment": "Testnet BeOne Chain",
    "rpc": [
        "https://pre-boc1.beonechain.com"
    ],
    "blockNumber": 251457
}

**Comment by Andey0** [comment]
https://t.me/Salmonation_Secretarybot  админ (не знаю почему он бот
https://t.me/salmonation  тг канал (чат)
https://github.com/beonechain/assets  рипозиторий
бридж есть на самом сайте
