### ISSUE TITLE
ADD 9818 tIMP

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#72]
{
    "chainId": 9818,
    "url": "https://imperiumchain.com",
    "ticker": "tIMP",
    "comment": "IMPERIUM TESTNET",
    "rpc": [
        "https://data-aws-testnet.imperiumchain.com",
        "https://data-aws2-testnet.imperiumchain.com"
    ],
    "blockNumber": 247744
}

**Comment by Andey0** [comment]
https://t.me/Imperium_Newss   анонсы  не показывало людей поэтому не могу написать кто админ 
https://github.com/imperiumchain/SolidityContract  рипозиторий
бридж (скоро выйдет)
