### ISSUE TITLE
ADD 9819 IMP

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#73]
{
    "chainId": 9819,
    "url": "https://imperiumchain.com",
    "ticker": "IMP",
    "comment": "IMPERIUM MAINNET",
    "rpc": [
        "https://data-aws-mainnet.imperiumchain.com",
        "https://data-aws2-mainnet.imperiumchain.com"
    ],
    "blockNumber": 222634
}

**Comment by Andey0** [comment]
https://t.me/imperiumchain_global  телеграмм
https://t.me/BiggestBuyTechBot  админ 
https://github.com/imperiumchain/SolidityContract  рипозиторий 
бридж есть
