### ISSUE TITLE
ADD 10243 AA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#74]
{
    "chainId": 10243,
    "url": "https://docs.arthera.net",
    "ticker": "AA",
    "comment": "Arthera Testnet",
    "rpc": [
        "https://rpc-test.arthera.net"
    ],
    "blockNumber": 77375
}

**Comment by Andey0** [comment]
https://t.me/artherachain/8  тг канал 
https://github.com/artheranet/evmone  рипозиторий
bridge нету
