### ISSUE TITLE
ADD 10395 WL

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#75]
{
    "chainId": 10395,
    "url": "https://worldland.foundation",
    "ticker": "WL",
    "comment": "Worldland Testnet",
    "rpc": [
        "https://gwangju.worldland.foundation"
    ],
    "blockNumber": 285036
}

**Comment by Andey0** [comment]
https://discord.com/invite/yJERYVnE6a  дискорд 
https://github.com/cryptoecc/ETH-ECC  рипозиторий 
бридж не нашел 
телеграмм не нашел
