### ISSUE TITLE
ADD 10508 NUM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#76]
{
    "chainId": 10508,
    "url": "https://numbersprotocol.io",
    "ticker": "NUM",
    "comment": "Numbers Testnet",
    "rpc": [
        "https://testnetrpc.num.network"
    ],
    "blockNumber": 57146
}

**Comment by Andey0** [comment]
https://t.me/numbersprotocol  телеграмм 
https://t.me/numbersprotocol  рипозиторий 
бридж не нашел 
админа телеграмма не нашел
