### ISSUE TITLE
ADD 16888 tIVAR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#78]
{
    "chainId": 16888,
    "url": "https://ivarex.com",
    "ticker": "tIVAR",
    "comment": "IVAR Chain Testnet",
    "rpc": [
        "https://testnet-rpc.ivarex.com"
    ],
    "blockNumber": 117034
}

**Comment by Andey0** [comment]
https://t.me/JhoneSwan  телеграмм анонсы
бридж есть 
гитхаба не нашел
