### ISSUE TITLE
ADD 18686 MXC

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#79]
{
    "chainId": 18686,
    "url": "https://doc.mxc.com/docs/intro",
    "ticker": "MXC",
    "comment": "MXC zkEVM Mainnet",
    "rpc": [
        "https://rpc.mxc.com"
    ],
    "blockNumber": 34384
}

**Comment by Andey0** [comment]
https://t.me/mxcfoundation-чат 
https://github.com/MXCzkEVM/SupernodeV2-devdocs-github
https://discord.com/invite/mxcfoundation-дискорд чат
brigde не нашол
