### ISSUE TITLE
ADD 38401 ttRPG

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#83]
{
    "chainId": 38401,
    "url": "https://rangersprotocol.com",
    "ticker": "ttRPG",
    "comment": "ConnectorManager Robin",
    "rpc": [
        "https://robin-cm.rangersprotocol.com/api/jsonrpc"
    ],
    "blockNumber": 9344
}

**Comment by Andey0** [comment]
https://t.me/RangersProtocol  телеграмм
https://t.me/JhoneSwan  модератор админа не нашел 
бридж нету
