### ISSUE TITLE
ADD 43288 BOBA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#85]
{
    "chainId": 43288,
    "url": "https://docs.boba.network/for-developers/network-avalanche",
    "ticker": "BOBA",
    "comment": "Boba Avax",
    "rpc": [
        "https://avax.boba.network",
        "wss://wss.avax.boba.network",
        "https://replica.avax.boba.network",
        "wss://replica-wss.avax.boba.network"
    ],
    "blockNumber": 94046
}

**Comment by Andey0** [comment]
https://github.com/omgnetwork/optimism  рипозиторий
https://t.me/bobadev  телеграмм 
https://t.me/KaoPad  админ 
бридж не нашел
