### ISSUE TITLE
ADD 55555 REI

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#87]
{
    "chainId": 55555,
    "url": "https://reichain.io",
    "ticker": "REI",
    "comment": "REI Chain Mainnet",
    "rpc": [
        "https://rei-rpc.moonrhythm.io"
    ],
    "blockNumber": 94400
}

**Comment by Andey0** [comment]
https://t.me/TGCHCHCH-админ тг
https://t.me/reichainglobal-сам тг чат
https://github.com/reichain/rei-репозитори
bridge не нашол
