### ISSUE TITLE
ADD 56789 NOVA

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#89]
{
    "chainId": 56789,
    "url": "https://velo.org",
    "ticker": "NOVA",
    "comment": "VELO Labs Mainnet",
    "rpc": [
        "https://nova.velo.org"
    ],
    "blockNumber": 5397
}

**Comment by Andey0** [comment]
https://t.me/veloprotocol  телеграмм 
https://t.me/HarveyVELO  админ
https://github.com/velo-protocol/DRSv2  рипозиторий
