### ISSUE TITLE
ADD 61800 AIUM

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#90]
{
    "chainId": 61800,
    "url": "https://www.axel.org",
    "ticker": "AIUM",
    "comment": "AxelChain Dev-Net",
    "rpc": [
        "https://aium-rpc-dev.viacube.com"
    ],
    "blockNumber": 48113
}

**Comment by Andey0** [comment]
https://t.me/nodester-админ
https://t.me/axelnetwork-чат 
Контакты Тони Тан (Генеральный директор и председатель) Бен Оу (Технический директор и президент)
bridge нету
