### ISSUE TITLE
ADD 84886 AER

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#94]
{
    "chainId": 84886,
    "url": "https://aerielab.io/",
    "ticker": "AER",
    "comment": "Aerie Network",
    "rpc": [
        "https://mainnet.aerielab.io"
    ],
    "blockNumber": 155829
}

**Comment by Andey0** [comment]
https://t.me/aerieofficial-телега
https://github.com/aerielabio/staking-deposit-cli-репозиторий
