### ISSUE TITLE
ADD 88888 IVAR

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#95]
{
    "chainId": 88888,
    "url": "https://ivarex.com",
    "ticker": "IVAR",
    "comment": "IVAR Chain Mainnet",
    "rpc": [
        "https://mainnet-rpc.ivarex.com"
    ],
    "blockNumber": 108098
}

**Comment by Andey0** [comment]
https://t.me/CoinMarketCapAnnouncements- телеги
https://twitter.com/CoinMarketCap-твиттер
