### ISSUE TITLE
ADD 200202 mTAlgo

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#96]
{
    "chainId": 200202,
    "url": "https://milkomeda.com",
    "ticker": "mTAlgo",
    "comment": "Milkomeda A1 Testnet",
    "rpc": [
        "https://rpc-devnet-algorand-rollup.a1.milkomeda.com"
    ],
    "blockNumber": 78383
}

**Comment by Andey0** [comment]
https://discord.com/invite/dcSpark-чат
больше  у них нечего не было

**Comment by Andey0** [comment]
https://discord.com/invite/dcSpark  дискорд 
телеграмма нету 
бридж нету 
гитхаба нету
