### ISSUE TITLE
ADD 355113 BFT

### ISSUE THREAD

**Issue by marsiandeployer** [noxonsu/chains#99]
{
    "chainId": 355113,
    "url": "https://bitfinity.network",
    "ticker": "BFT",
    "comment": "Bitfinity Network Testnet",
    "rpc": [
        "https://testnet.bitfinity.network"
    ],
    "blockNumber": 221712
}

**Comment by Andey0** [comment]
https://t.me/infinityswapofficial анонсы
https://discord.com/invite/zrsZzR635r дискорд-форум
https://github.com/bitfinity-network/ethers.js рипозитори
контактов не было 
bridge не было
